### ISSUE TITLE
simpleaf index: long runtime | takes too long

### ISSUE THREAD

**Issue by robertzeibich** [COMBINE-lab/simpleaf#161]
Should `simpleaf index` take that long?

JobID         Partition    JobName      User      State    **Elapsed**    CPUTime ReqNodes   NNodes     ReqMem     MaxRSS  ReqCPUS
40578412_1      desktop      index  rzei0002  COMPLETED   **11:34:35** 11-13:50:00        1        1       200G                  24
40578412_1.+                 batch            COMPLETED   **11:34:35** 11-13:50:00        1        1             15791940K       24
40578412_1.+                extern            COMPLETED   **11:34:35** 11-13:50:00        1        1                     0       24

**Comment by rob-p** [comment]
The indexing procedure should generally be quite fast. The caveat here is that to keep working memory small, both the underlying de Bruijn graph constructor (cuttlefish) and the underlying hash function generator (PTHash) generate many small intermediate files. While this should be fast to write and read, they can wreak havoc on a networked file system.  If you are running this on a cluster (it looks like you are), you should ensure that you set the index output location and the working directory to be fast local scratch disk. You can then copy the constructed index directly to wherever you want it to reside on the networked file system.

**Comment by robertzeibich** [comment]
I run the script on `projects` and write the files to `scratch `directory:

> found `piscem` in the PATH at /scratch/xm41/rzei0002/miniconda/conda/envs/af/bin/piscem
> found `salmon` in the PATH at /scratch/xm41/rzei0002/miniconda/conda/envs/af/bin/salmon
> found `alevin-fry` in the PATH at /scratch/xm41/rzei0002/miniconda/conda/envs/af/bin/alevin-fry
> 24
> simpleaf index --output /scratch/xm41/hg38_resources/scRNA/refdata-gex-GRCh38-2020-A/human-2020-A_splici/91 --fasta /scratch/xm41/hg38_resources/scRNA/refdata-gex-GRCh38-2020-A/fasta/genome.fa --gtf /scratch/xm41/hg38_resources/scRNA/ref
> data-gex-GRCh38-2020-A/genes/genes.gtf --rlen 91 --threads 24 --use-piscem
> 2024-10-18T10:04:54.379643Z  INFO simpleaf::simpleaf_commands::indexing: preparing to make reference with roers
> 2024-10-18T10:05:10.536583Z  INFO grangers::reader::gtf: Finished parsing the input file. Found 5 comments and 2765969 records.
> 2024-10-18T10:05:13.841246Z  INFO roers: Built the Grangers object for 2765969 records
> 2024-10-18T10:05:14.735096Z  INFO roers: Proceed 1305354 exon records from 199138 transcripts
> 2024-10-18T10:05:34.059823Z  INFO roers: Processing 1106216 intronic records
> 2024-10-18T10:06:13.537922Z  INFO roers: Done!
> 2024-10-18T10:06:13.545278Z  INFO simpleaf::simpleaf_commands::indexing: piscem build cmd : /scratch/xm41/rzei0002/miniconda/conda/envs/af/bin/piscem build -k 31 -m 19 -o /scratch/xm41/hg38_resources/scRNA/refdat
> a-gex-GRCh38-2020-A/human-2020-A_splici/91/index/piscem_idx -s /scratch/xm41/hg38_resources/scRNA/refdata-gex-GRCh38-2020-A/human-2020-A_splici/91/ref/roers_ref.fa --seed 1 --threads 24
> 2024-10-18T21:39:24.630690Z  INFO simpleaf::utils::prog_utils: command returned successfully (exit status: 0)

Yesterday, I also noticed the following error:

> Error removing the KMC database file from path prefix ./workdir.noindex/piscem_idx_cfish.cf_V. Aborting.

Problem: I wanted to create multiple indices at the same time. 

I could generate the index in a conda environment on my local computer (windows). Do you think that would be better?

**Comment by robertzeibich** [comment]
**HPC execution issue**

I executed `simpleaf `under `projects` and wrote the output to `scratch`.  Runtime: 12 hours+

When I execute `simpleaf `and write the output to `tmp` and then move the generated index to scratch after the process completes, the runtime improves drastically. Runtime: <3 hours.

**Comment by wmacnair** [comment]
I have had similar issues, although slightly worse: in addition to long run times, on our cluster `simpleaf` doesn't successfully clean up the tiny intermediate files. As a result I got a "disk quota exceeded" error, due to a process I started generating 1.1M files... (I remember having the same issue about a year ago too.)

A couple of thoughts:

I would assume that this is difficult to fix, as this is a fundamental part of how the software was implemented. One thought is whether increasing the size of the tiny files could help. So then on a cluster you can take advantage of many CPUs, but do less IO (thus managing the non-fast disk issue). But maybe it's not as simple as that?

If a fix is not possible, is this something that could be caught? Perhaps a test that the selected location has enough IO speed, or an occasional check of how many _cuttlefish-path-output-..._ files have been made, which stops the process if deletion isn't keeping up with creation.

We're in the process of testing a larger single cell workflow where the mapping steps are based on simpleaf, and it would be fantastic if the index-building step could be made more reliable on clusters 🙏

Best
Will
