### ISSUE TITLE
Using simpleaf quant offline

### ISSUE THREAD

**Issue by jagoor93** [COMBINE-lab/simpleaf#88]
Good afternoon,
Due to server limitations, I can't connect to the internet while running a submitted job. Therefore, I can't run simpleaf quant as shown in this tutorial https://combine-lab.github.io/alevin-fry-tutorials/2023/simpleaf-piscem/ because I can't download the external permit list. Is there any possible workaround for this issue? Please, let me know if this is the appropriate place to submit this post.
Thank you very much for your tutorials; they are very helpful!
Kind regards
Javier

**Comment by rob-p** [comment]
Hi @jagoor93,

  Thanks for your question.  This is the appropriate venue for this.  The automatic fetching of the external permit list during the `simpleaf quant` step is something that only happens if (a) an explicit permit list location is not given and (b) the corresponding permit list is not already present in the expected location on the local machine.  Further, it will only happen the first time such a quantification call is performed.

To avoid an attempt at downloading and decompressing this list during `simpleaf quant`, you can either pre-populate the `ALEVIN_FRY_HOME` directory with the appropriate files (i.e. `$ALEVIN_FRY_HOME/plist/10x_v2_permit.txt` and `$ALEVIN_FRY_HOME/plist/10x_v3_permit.txt`).  You can obtain the first file from [here](https://umd.box.com/shared/static/jbs2wszgbj7k4ic2hass9ts6nhqkwq1p) and the second from [here](https://umd.box.com/shared/static/eo0qlkfqf2v24ws6dfnxty6gqk1otf2h).  Alternatively, you can explicitly provide the path to the unfiltered permit list that you wish to use to the `-u` argument during the `quant` step, and `simpleaf` will use that permit list rather than attempt to fetch the corresponding one directly from the internet.

Please let us know if this works for you (cc @DongzeHE in case he has any extra thoughts on this).

--Rob

**Comment by rob-p** [comment]
I'll assume this addresses the issue, but feel free to re-open if not.
